# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='infopage.Approach')),
            ],
            options={
                'verbose_name_plural': 'approach',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='infopage.Specialty')),
            ],
            options={
                'verbose_name_plural': 'approach',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('irisLink', models.TextField(default='')),
                ('faculty', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('approach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infopage.Approach')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infopage.Specialty')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='specialty',
            unique_together=set([('slug', 'parent')]),
        ),
        migrations.AlterUniqueTogether(
            name='approach',
            unique_together=set([('slug', 'parent')]),
        ),
    ]
