# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infopage', '0002_auto_20171116_1452'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approach',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='approach',
            name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='specialty',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='approach',
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialty',
        ),
        migrations.DeleteModel(
            name='Approach',
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
