# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infopage', '0005_bsds_bshf_bsi_bsm_ccds_cchf_cci_ccm_chds_chhf_chi_chm_mds_mhf_mi_mm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Entry',
        ),
    ]
