# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infopage', '0006_auto_20171121_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='description',
        ),
        migrations.AddField(
            model_name='entry',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
    ]
